// <auto-generated />
namespace WalkingDinnerWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class v24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v24));
        
        string IMigrationMetadata.Id
        {
            get { return "202004241536599_v24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
